POST http://localhost:8010/orders HTTP/1.1
Content-Type: application/json

{
    "email": "john.doe@email.com",
    "items": [
        {
            "productId": "96ce7305-c5ad-462f-95a6-c7ea1f7e9133",
            "amount": 2
        } 
    ]
}