### Create Product
POST http://localhost:8010/admin/products HTTP/1.1
Content-Type: application/json

{
    "name": "Product 1",
    "price": 1000,
    "currency": "usd"
}

### 
@productId=0b915311-a97c-48d3-9ca0-918ab762f989

### Update product
PUT http://localhost:8010/admin/products/{{productId}} HTTP/1.1
Content-Type: application/json

{
    "name": "Updated Product 1",
    "price": 3050
}