# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql
        ports:
          - 3306
        env:
          MYSQL_USER: user
          MYSQL_PASSWORD: 123456
          MYSQL_DATABASE: app
          MYSQL_ROOT_PASSWORD: 123456
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3

      - name: Run Migrations
        run: mysql --host 127.0.0.1 --port=${{ job.services.mysql.ports[3306] }} -uroot --password=123456 app < ./migrations/database.sql

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm install
      - run: npm run lint
      - run: npm test
        env:
          DB_TYPE: mysql
          DB_PORT: ${{ job.services.mysql.ports[3306] }}
          DB_HOST: 127.0.0.1
          DB_USER: root
          DB_PASS: 123456
          DB_NAME: app
